# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: commitizen
builds:
  - env:
      - CGO_ENABLED=0
      - VERSION_PACKAGE=github.com/robertzhangwenjie/commitizen/pkg/version
      - GIT_TREE_STATE=clean
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X '{{.Env.VERSION_PACKAGE}}.GitCommit={{.Env.GitCommit}}'
      - -X '{{.Env.VERSION_PACKAGE}}.BuildTime={{.Env.BuildTime}}'
      - -X '{{.Env.VERSION_PACKAGE}}.GoVersion={{.Env.GoVersion}}'
      - -X '{{.Env.VERSION_PACKAGE}}.GitVersion={{.Env.GitVersion}}'
      - -X '{{.Env.VERSION_PACKAGE}}.GitTreeState={{.Env.GIT_TREE_STATE}}'
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
