name: goreleaser

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set env
        run: echo "GOVERSION=$(go version | awk -F" " '{print $3,$4}') \
        GitCommit=$(git rev-parse --short HEAD) \
        BuildTime=$(date "+%Y-%m-%d %H:%M:%S") \
        GoVersion=$(echo ${$(go version):2}) \
        GitVersion=$(git tag | tail -1) \
        " >> $GITHUB_ENV

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: commitizen
          path: dist/*
